part of 'page_rhythm_phone_visual_qa_test_utils.dart';

const pageRhythmGiuVisualQaFlows = [
  VisualQaFlow(
    id: 43,
    name: 'Markets tab root (compact 8px sections)',
    route: AppRoutePaths.markets,
    semanticLabel: 'Thị trường',
    expectBottomNav: true,
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 44,
    name: 'Trade tab root (compact 8px sections)',
    route: AppRoutePaths.trade,
    semanticLabel: 'Giao dịch Spot',
    expectBottomNav: true,
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 45,
    name: 'Unified search (compact discovery)',
    route: AppRoutePaths.search,
    semanticLabel: 'Tìm kiếm',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 46,
    name: 'Notifications header entry',
    route: AppRoutePaths.notifications,
    semanticLabel: 'Thông báo',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 47,
    name: 'Margin trading risk review',
    route: AppRoutePaths.tradeMargin,
    semanticLabel: 'Giao dịch ký quỹ',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 48,
    name: 'Trade convert form',
    route: AppRoutePaths.tradeConvert,
    semanticLabel: 'Chuyển đổi tài sản',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 49,
    name: 'Copy trading hub',
    route: AppRoutePaths.tradeCopyTrading,
    semanticLabel: 'Sao chép giao dịch – sao chép chiến lược có kiểm soát',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 50,
    name: 'Trading bots hub',
    route: AppRoutePaths.tradeBots,
    semanticLabel: 'Bot giao dịch tự động',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 51,
    name: 'Earn home',
    route: AppRoutePaths.earn,
    semanticLabel:
        'Trang chủ Earn & Stake — sản phẩm tiết kiệm lãi cố định, linh hoạt và các vị thế đang sinh lời',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 52,
    name: 'Savings home',
    route: AppRoutePaths.earnSavings,
    semanticLabel: 'Tiết kiệm',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 53,
    name: 'Launchpad hub',
    route: AppRoutePaths.launchpad,
    semanticLabel: 'Trung tâm dự án Launchpad',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 54,
    name: 'Prediction markets hub',
    route: AppRoutePaths.marketsPredictions,
    semanticLabel: 'Trang chủ thị trường dự đoán: xác suất và sự kiện đang mở',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 55,
    name: 'Referral home',
    route: AppRoutePaths.referral,
    semanticLabel: 'Giới thiệu bạn bè',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 56,
    name: 'Support hub',
    route: AppRoutePaths.support,
    semanticLabel: 'Hỗ trợ',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 57,
    name: 'Trade orders history',
    route: AppRoutePaths.tradeOrdersHistory,
    semanticLabel: 'Lịch sử lệnh giao dịch',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 58,
    name: 'Trade positions',
    route: AppRoutePaths.tradePositions,
    semanticLabel: 'Vị thế đang mở',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 59,
    name: 'Earn dashboard',
    route: AppRoutePaths.earnDashboard,
    semanticLabel:
        'Bảng điều khiển staking — hiệu suất, phân bổ tài sản và các vị thế đang stake',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 60,
    name: 'Savings portfolio',
    route: AppRoutePaths.earnSavingsPortfolio,
    semanticLabel: 'Danh mục tiết kiệm',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 61,
    name: 'News home header entry',
    route: AppRoutePaths.news,
    semanticLabel: 'Tin tức & Thông báo',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 62,
    name: 'Topic hub',
    route: AppRoutePaths.topics,
    semanticLabel: 'Trung tâm chủ đề',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 63,
    name: 'Settings security',
    route: AppRoutePaths.settingsSecurity,
    semanticLabel: 'SC-413 SettingsSecurity',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 64,
    name: 'Profile KYC',
    route: AppRoutePaths.profileKyc,
    semanticLabel: 'Xác minh danh tính',
    assertStandardContentWidth: true,
  ),
  // Auth login is outside the app shell and has no VitCard width surface.
  VisualQaFlow(
    id: 65,
    name: 'Auth login shell',
    route: AppRoutePaths.authLogin,
    semanticLabel: 'Đăng nhập',
  ),
];
