// Origin: 905aebcd (2026-07-07) - feat(flutter): chuẩn hóa UI toàn app theo 6 tiêu chuẩn thiết kế
// Guardrail này có lý do tồn tại riêng - đọc commit gốc ở trên trước khi nới lỏng hoặc xóa.
// Tách từ page_rhythm_phone_visual_qa_test.dart 2026-07-20 (giới hạn 400 dòng/file test).
import 'package:vit_trade_flutter/app/router/app_router.dart';

part 'page_rhythm_phone_visual_qa_test_utils_giu.dart';

class VisualQaFlow {
  const VisualQaFlow({
    required this.id,
    required this.name,
    required this.route,
    required this.semanticLabel,
    this.expectBottomNav = false,
    this.assertStandardContentWidth = false,
  });

  final int id;
  final String name;
  final String route;
  final String semanticLabel;
  final bool expectBottomNav;
  final bool assertStandardContentWidth;
}

const pageRhythmVisualQaFlows = [
  VisualQaFlow(
    id: 1,
    name: 'Home tab root (compact 8px)',
    route: AppRoutePaths.home,
    semanticLabel: 'Trang chủ',
    expectBottomNav: true,
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 2,
    name: 'Wallet multi-manager (standard 13px)',
    route: AppRoutePaths.walletMultiManager,
    semanticLabel: 'Quản lý đa ví - kiểm soát địa chỉ và sao chép',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 3,
    name: 'Savings Guide (form 16px)',
    route: AppRoutePaths.earnSavingsGuide,
    semanticLabel: 'Hướng dẫn Tiết kiệm',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 4,
    name: 'P2P Merchant Apply (form 16px)',
    route: AppRoutePaths.p2pMerchantApply,
    semanticLabel: 'Đăng ký Merchant P2P',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 5,
    name: 'Arena home (compact 8px)',
    route: AppRoutePaths.arena,
    semanticLabel:
        'Trang chủ Open Arena - khám phá và tham gia thử thách công bằng',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 6,
    name: 'Settings scroll (standard 13px)',
    route: AppRoutePaths.profileSettings,
    semanticLabel: 'Cài đặt tài khoản',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 7,
    name: 'Admin analytics (standard 13px)',
    route: AppRoutePaths.adminAnalytics,
    semanticLabel: 'Bảng phân tích dữ liệu',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 8,
    name: 'Copy Trading provider apply (form 16px)',
    route: AppRoutePaths.tradeCopyProviderApply,
    semanticLabel: 'Đăng ký Provider',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 9,
    name: 'Cross-module portfolio (standard 13px)',
    route: AppRoutePaths.unifiedPortfolio,
    semanticLabel: 'Danh mục đầu tư hợp nhất',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 10,
    name: 'Markets depth (flush + form inner)',
    route: AppRoutePaths.marketsDepth,
    semanticLabel: 'Độ sâu thị trường',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 11,
    name: 'Home product grid (Tier B badges)',
    route: AppRoutePaths.home,
    semanticLabel: 'Trang chủ',
    expectBottomNav: true,
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 12,
    name: 'Rewards task list (VitTaskCard Tier E)',
    route: AppRoutePaths.rewards,
    semanticLabel: 'Trung tâm Phần thưởng',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 13,
    name: 'P2P home (compact ad rows)',
    route: AppRoutePaths.p2p,
    semanticLabel: 'Trang chủ giao dịch P2P',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 14,
    name: 'DCA home (overview metrics)',
    route: AppRoutePaths.dca,
    semanticLabel: 'Mua tự động (DCA) – đầu tư định kỳ có kỷ luật',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 15,
    name: 'Trader profile (hero copiers row)',
    route: '/trade/trader/demo',
    semanticLabel: 'Hồ sơ trader',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 16,
    name: 'Referral history (friend cards)',
    route: AppRoutePaths.referralHistory,
    semanticLabel: 'Lịch sử giới thiệu',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 17,
    name: 'Markets correlations (underline tabs)',
    route: AppRoutePaths.marketsCorrelations,
    semanticLabel: 'Tương quan thị trường',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 18,
    name: 'Savings analytics (chart header)',
    route: AppRoutePaths.earnSavingsAnalytics,
    semanticLabel: 'Phân tích Tiết kiệm',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 19,
    name: 'Arena leaderboard (season filters)',
    route: AppRoutePaths.arenaLeaderboard,
    semanticLabel: 'Bảng xếp hạng fair play trong Open Arena',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 20,
    name: 'Wallet withdraw (form 16px sections)',
    route: AppRoutePaths.walletWithdraw,
    semanticLabel: 'Rút tiền',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 21,
    name: 'Wallet deposit (form 16px sections)',
    route: AppRoutePaths.walletDeposit,
    semanticLabel: 'Nạp tiền',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 22,
    name: 'Wallet transfer (form 16px sections)',
    route: AppRoutePaths.walletTransfer,
    semanticLabel: 'Chuyển nội bộ',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 23,
    name: 'Wallet buy crypto (form 16px sections)',
    route: AppRoutePaths.walletBuyCrypto,
    semanticLabel: 'Mua tiền mã hoá',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 24,
    name: 'Wallet address add (form 16px sections)',
    route: AppRoutePaths.walletAddressBookAdd,
    semanticLabel: 'Thêm địa chỉ mới vào sổ địa chỉ ví',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 25,
    name: 'Wallet dust converter (form 16px sections)',
    route: AppRoutePaths.walletDustConverter,
    semanticLabel: 'Chuyển đổi số dư nhỏ',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 26,
    name: 'Wallet withdraw limits (form 16px sections)',
    route: AppRoutePaths.walletLimits,
    semanticLabel: 'Hạn mức rút tiền theo cấp KYC',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 27,
    name: 'Wallet token approval (form 16px sections)',
    route: AppRoutePaths.walletTokenApproval,
    semanticLabel: 'Phê duyệt token - xem và thu hồi quyền truy cập',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 28,
    name: 'Wallet tx history (standard 13px sections)',
    route: AppRoutePaths.walletHistory,
    semanticLabel: 'Lịch sử giao dịch - theo dõi nạp, rút an toàn',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 29,
    name: 'Wallet asset detail (standard 13px sections)',
    route: '/wallet/asset/btc',
    semanticLabel: 'Chi tiết tài sản - số dư minh bạch',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 30,
    name: 'Wallet address book (standard 13px sections)',
    route: AppRoutePaths.walletAddressBook,
    semanticLabel: 'Sổ địa chỉ - quản lý địa chỉ ví đã lưu',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 31,
    name: 'Wallet portfolio analytics (standard 13px)',
    route: AppRoutePaths.walletPortfolioAnalytics,
    semanticLabel: 'Phân tích danh mục - tổng quan tài sản',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 32,
    name: 'Wallet network status (standard 13px sections)',
    route: AppRoutePaths.walletNetworkStatus,
    semanticLabel: 'Trạng thái mạng - phí, độ trễ và tắc nghẽn',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 33,
    name: 'Wallet tab root (compact 8px sections)',
    route: AppRoutePaths.wallet,
    semanticLabel: 'Ví - số dư minh bạch, bảo mật đa lớp',
    expectBottomNav: true,
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 34,
    name: 'Wallet pending deposits (standard 13px sections)',
    route: AppRoutePaths.walletPendingDeposits,
    semanticLabel: 'Nạp tiền đang chờ xác nhận',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 35,
    name: 'Wallet gas optimizer (standard 13px sections)',
    route: AppRoutePaths.walletGasOptimizer,
    semanticLabel: 'Tối ưu phí gas giao dịch trên mạng',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 36,
    name: 'Wallet health score (standard 13px sections)',
    route: AppRoutePaths.walletHealthScore,
    semanticLabel: 'Điểm sức khỏe ví - tổng quan, bảo mật và đa dạng hóa',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 37,
    name: 'Wallet portfolio analytics overview sections',
    route: AppRoutePaths.walletPortfolioAnalytics,
    semanticLabel: 'Phân tích danh mục - tổng quan tài sản',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 38,
    name: 'Wallet token approval tab sections (form 16px)',
    route: AppRoutePaths.walletTokenApproval,
    semanticLabel: 'Phê duyệt token - xem và thu hồi quyền truy cập',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 39,
    name: 'Wallet multi-manager tab sections (standard 13px)',
    route: AppRoutePaths.walletMultiManager,
    semanticLabel: 'Quản lý đa ví - kiểm soát địa chỉ và sao chép',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 40,
    name: 'Wallet transaction detail (standard 13px sections)',
    route: '/wallet/transaction/tx001',
    semanticLabel: 'Chi tiết giao dịch',
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 41,
    name: 'Profile hub (account cards)',
    route: AppRoutePaths.profile,
    semanticLabel: 'Trang tài khoản: hồ sơ cá nhân, giới thiệu bạn bè và VIP',
    expectBottomNav: true,
    assertStandardContentWidth: true,
  ),
  VisualQaFlow(
    id: 42,
    name: 'P2P dashboard (merchant metrics)',
    route: AppRoutePaths.p2pDashboard,
    semanticLabel: 'Tổng quan P2P',
    assertStandardContentWidth: true,
  ),
  ...pageRhythmGiuVisualQaFlows,
];
