import 'package:vit_trade_flutter/app/router/app_router.dart';

import 'app_route_names_contract_test_utils.dart';

void main() {
  routeNameContractTest(
    'defines stable wallet profile DCA and admin route names',
    [
      n(AppRouteNames.sc135Wallet, 'sc135Wallet'),
      n(AppRouteNames.sc136TxHistory, 'sc136TxHistory'),
      n(AppRouteNames.sc137Deposit, 'sc137Deposit'),
      n(AppRouteNames.sc138DepositUsdt, 'sc138DepositUsdt'),
      n(AppRouteNames.sc139Withdraw, 'sc139Withdraw'),
      n(AppRouteNames.sc140WithdrawUsdt, 'sc140WithdrawUsdt'),
      n(AppRouteNames.sc141TransactionDetail, 'sc141TransactionDetail'),
      n(AppRouteNames.sc142PortfolioAnalytics, 'sc142PortfolioAnalytics'),
      n(AppRouteNames.sc143AddressAdd, 'sc143AddressAdd'),
      n(AppRouteNames.sc144AddressBook, 'sc144AddressBook'),
      n(AppRouteNames.sc145BuyCrypto, 'sc145BuyCrypto'),
      n(AppRouteNames.sc146Transfer, 'sc146Transfer'),
      n(AppRouteNames.sc147AssetDetail, 'sc147AssetDetail'),
      n(AppRouteNames.sc148MultiManager, 'sc148MultiManager'),
      n(AppRouteNames.sc149GasOptimizer, 'sc149GasOptimizer'),
      n(AppRouteNames.sc150TokenApproval, 'sc150TokenApproval'),
      n(AppRouteNames.sc151HealthScore, 'sc151HealthScore'),
      n(AppRouteNames.sc152PendingDeposits, 'sc152PendingDeposits'),
      n(AppRouteNames.sc153WithdrawLimits, 'sc153WithdrawLimits'),
      n(AppRouteNames.sc154DustConverter, 'sc154DustConverter'),
      n(AppRouteNames.sc155NetworkStatus, 'sc155NetworkStatus'),
      n(AppRouteNames.sc156Profile, 'sc156Profile'),
      n(AppRouteNames.sc157EditProfile, 'sc157EditProfile'),
      n(AppRouteNames.sc158Security, 'sc158Security'),
      n(AppRouteNames.sc159Kyc, 'sc159Kyc'),
      n(AppRouteNames.sc160Settings, 'sc160Settings'),
      n(AppRouteNames.sc161ActivityLog, 'sc161ActivityLog'),
      n(AppRouteNames.sc162ApiKeyCreate, 'sc162ApiKeyCreate'),
      n(AppRouteNames.sc163ApiManagement, 'sc163ApiManagement'),
      n(AppRouteNames.sc164Vip, 'sc164Vip'),
      n(AppRouteNames.sc165DeviceManagement, 'sc165DeviceManagement'),
      n(AppRouteNames.sc166SubAccount, 'sc166SubAccount'),
      n(AppRouteNames.sc167ProfilePredictions, 'sc167ProfilePredictions'),
      n(AppRouteNames.sc168MyArena, 'sc168MyArena'),
      n(AppRouteNames.sc169Dca, 'sc169Dca'),
      n(AppRouteNames.sc170DcaRebalanceConfig, 'sc170DcaRebalanceConfig'),
      n(AppRouteNames.sc171DcaRebalanceDashboard, 'sc171DcaRebalanceDashboard'),
      n(AppRouteNames.sc172DcaScheduleConfig, 'sc172DcaScheduleConfig'),
      n(AppRouteNames.sc173DcaScheduleAnalytics, 'sc173DcaScheduleAnalytics'),
      n(AppRouteNames.sc174DcaPortfolioOptimizer, 'sc174DcaPortfolioOptimizer'),
      n(AppRouteNames.sc175DcaDynamicAmount, 'sc175DcaDynamicAmount'),
      n(AppRouteNames.sc176DcaBacktester, 'sc176DcaBacktester'),
      n(AppRouteNames.sc177DcaMultiAsset, 'sc177DcaMultiAsset'),
      n(AppRouteNames.sc178DcaPerformanceCompare, 'sc178DcaPerformanceCompare'),
      n(AppRouteNames.sc179DcaSmartRules, 'sc179DcaSmartRules'),
      n(AppRouteNames.sc180AdminHome, 'sc180AdminHome'),
      n(AppRouteNames.sc181AnalyticsDashboard, 'sc181AnalyticsDashboard'),
      n(AppRouteNames.sc182AbTestDashboard, 'sc182AbTestDashboard'),
      n(AppRouteNames.sc183FunnelDashboard, 'sc183FunnelDashboard'),
      n(
        AppRouteNames.sc405SettingsSecurityBiometric,
        'sc405SettingsSecurityBiometric',
      ),
      n(
        AppRouteNames.sc406SettingsSecurityChangePassword,
        'sc406SettingsSecurityChangePassword',
      ),
      n(AppRouteNames.sc408DcaRebalanceEdit, 'sc408DcaRebalanceEdit'),
      n(AppRouteNames.sc409DcaRebalanceHistory, 'sc409DcaRebalanceHistory'),
      n(AppRouteNames.sc410AdminSettings, 'sc410AdminSettings'),
      n(AppRouteNames.sc413SettingsSecurity, 'sc413SettingsSecurity'),
    ],
  );
}
