import 'package:vit_trade_flutter/app/router/app_router.dart';

import 'app_route_names_contract_test_utils.dart';

void main() {
  routeNameContractTest('defines stable trade route names', [
    n(AppRouteNames.sc044PairDetail, 'sc044PairDetail'),
    n(AppRouteNames.sc045TokenInfo, 'sc045TokenInfo'),
    n(AppRouteNames.sc046PairDepth, 'sc046PairDepth'),
    n(AppRouteNames.sc047News, 'sc047News'),
    n(AppRouteNames.sc048Trade, 'sc048Trade'),
    n(AppRouteNames.sc049TradePair, 'sc049TradePair'),
    n(AppRouteNames.sc050OrdersHistory, 'sc050OrdersHistory'),
    n(AppRouteNames.sc051OrderReceipt, 'sc051OrderReceipt'),
    n(AppRouteNames.sc052TradeSettings, 'sc052TradeSettings'),
    n(AppRouteNames.sc053PositionDashboard, 'sc053PositionDashboard'),
    n(AppRouteNames.sc054TradeHistoryExport, 'sc054TradeHistoryExport'),
    n(AppRouteNames.sc055AdvancedChart, 'sc055AdvancedChart'),
    n(AppRouteNames.sc056Convert, 'sc056Convert'),
    n(AppRouteNames.sc057Futures, 'sc057Futures'),
    n(AppRouteNames.sc058Leverage, 'sc058Leverage'),
    n(AppRouteNames.sc059TradingBots, 'sc059TradingBots'),
    n(AppRouteNames.sc060RiskManagement, 'sc060RiskManagement'),
    n(AppRouteNames.sc061ExecutionQuality, 'sc061ExecutionQuality'),
    n(AppRouteNames.sc062AdvancedTools, 'sc062AdvancedTools'),
    n(AppRouteNames.sc063CopyTrading, 'sc063CopyTrading'),
    n(AppRouteNames.sc065CopyEducation, 'sc065CopyEducation'),
    n(AppRouteNames.sc066ActiveCopies, 'sc066ActiveCopies'),
    n(AppRouteNames.sc067CopySettings, 'sc067CopySettings'),
    n(AppRouteNames.sc068CopyNotifications, 'sc068CopyNotifications'),
    n(AppRouteNames.sc069ProviderApplication, 'sc069ProviderApplication'),
    n(AppRouteNames.sc070CopyProviderDetail, 'sc070CopyProviderDetail'),
    n(AppRouteNames.sc071PreCopyAssessment, 'sc071PreCopyAssessment'),
    n(AppRouteNames.sc072CopyConfiguration, 'sc072CopyConfiguration'),
    n(AppRouteNames.sc073CopyConfirmation, 'sc073CopyConfirmation'),
    n(AppRouteNames.sc074CopyPerformance, 'sc074CopyPerformance'),
    n(AppRouteNames.sc075PerformanceAttribution, 'sc075PerformanceAttribution'),
    n(AppRouteNames.sc076ProviderComparison, 'sc076ProviderComparison'),
    n(AppRouteNames.sc077CopyAuditLog, 'sc077CopyAuditLog'),
    n(AppRouteNames.sc078PortfolioRiskAnalysis, 'sc078PortfolioRiskAnalysis'),
    n(AppRouteNames.sc079ProviderLeaderboard, 'sc079ProviderLeaderboard'),
    n(AppRouteNames.sc080SafetyEducation, 'sc080SafetyEducation'),
    n(AppRouteNames.sc081ProviderGovernance, 'sc081ProviderGovernance'),
    n(AppRouteNames.sc082DisputeResolution, 'sc082DisputeResolution'),
    n(AppRouteNames.sc083CopySafetyCenter, 'sc083CopySafetyCenter'),
    n(AppRouteNames.sc084RegulatoryDisclosures, 'sc084RegulatoryDisclosures'),
    n(AppRouteNames.sc085MarginTrading, 'sc085MarginTrading'),
    n(AppRouteNames.sc086MarginTradingPair, 'sc086MarginTradingPair'),
    n(AppRouteNames.sc087TraderProfile, 'sc087TraderProfile'),
    n(AppRouteNames.sc088AdvancedTradingDemo, 'sc088AdvancedTradingDemo'),
    n(AppRouteNames.sc089MarketDataAnalytics, 'sc089MarketDataAnalytics'),
    n(AppRouteNames.sc090MarginTradingHub, 'sc090MarginTradingHub'),
    n(
      AppRouteNames.sc091LiveMarketDataAnalytics,
      'sc091LiveMarketDataAnalytics',
    ),
    n(AppRouteNames.sc092AdvancedAnalytics, 'sc092AdvancedAnalytics'),
    n(AppRouteNames.sc093TransactionReporting, 'sc093TransactionReporting'),
    n(
      AppRouteNames.sc094RegulatoryReportsDashboard,
      'sc094RegulatoryReportsDashboard',
    ),
    n(AppRouteNames.sc095ArmIntegrationStatus, 'sc095ArmIntegrationStatus'),
    n(AppRouteNames.sc096BestExecutionReports, 'sc096BestExecutionReports'),
    n(AppRouteNames.sc097ExecutionVenueAnalysis, 'sc097ExecutionVenueAnalysis'),
    n(AppRouteNames.sc098SlippageMonitoring, 'sc098SlippageMonitoring'),
    n(AppRouteNames.sc099ClientCategorization, 'sc099ClientCategorization'),
    n(AppRouteNames.sc100ProductGovernance, 'sc100ProductGovernance'),
    n(AppRouteNames.sc101TargetMarketDefinition, 'sc101TargetMarketDefinition'),
    n(AppRouteNames.sc102ClientMoneyProtection, 'sc102ClientMoneyProtection'),
    n(AppRouteNames.sc103CassReconciliation, 'sc103CassReconciliation'),
    n(AppRouteNames.sc104InvestorCompensation, 'sc104InvestorCompensation'),
    n(AppRouteNames.sc105ExAnteCosts, 'sc105ExAnteCosts'),
    n(AppRouteNames.sc106RiyCalculator, 'sc106RiyCalculator'),
    n(AppRouteNames.sc107ExPostCostsReport, 'sc107ExPostCostsReport'),
    n(AppRouteNames.sc108KidGenerator, 'sc108KidGenerator'),
    n(AppRouteNames.sc109PerformanceScenarios, 'sc109PerformanceScenarios'),
    n(AppRouteNames.sc110RiskIndicatorExplainer, 'sc110RiskIndicatorExplainer'),
    n(AppRouteNames.sc111ComplaintsHandling, 'sc111ComplaintsHandling'),
    n(AppRouteNames.sc112ComplaintSubmission, 'sc112ComplaintSubmission'),
    n(AppRouteNames.sc113ComplaintTracking, 'sc113ComplaintTracking'),
    n(AppRouteNames.sc114OmbudsmanReferral, 'sc114OmbudsmanReferral'),
    n(AppRouteNames.sc115AuditTrail, 'sc115AuditTrail'),
    n(
      AppRouteNames.sc116RegulatoryInspectionReady,
      'sc116RegulatoryInspectionReady',
    ),
    n(AppRouteNames.sc117BotTermsOfService, 'sc117BotTermsOfService'),
    n(AppRouteNames.sc118BotRiskDisclosure, 'sc118BotRiskDisclosure'),
    n(
      AppRouteNames.sc119BotSuitabilityAssessment,
      'sc119BotSuitabilityAssessment',
    ),
    n(AppRouteNames.sc120BotRiskDashboard, 'sc120BotRiskDashboard'),
    n(AppRouteNames.sc121BotEmergencyStop, 'sc121BotEmergencyStop'),
    n(AppRouteNames.sc122BotSecuritySettings, 'sc122BotSecuritySettings'),
    n(AppRouteNames.sc123BotHistory, 'sc123BotHistory'),
    n(
      AppRouteNames.sc124BotPerformanceAnalytics,
      'sc124BotPerformanceAnalytics',
    ),
    n(AppRouteNames.sc125BotBacktesting, 'sc125BotBacktesting'),
    n(AppRouteNames.sc126BotStrategyCompare, 'sc126BotStrategyCompare'),
    n(AppRouteNames.sc127BotOptimization, 'sc127BotOptimization'),
    n(AppRouteNames.sc128BotPortfolioDashboard, 'sc128BotPortfolioDashboard'),
    n(AppRouteNames.sc129BotDrawdownAnalyzer, 'sc129BotDrawdownAnalyzer'),
    n(AppRouteNames.sc130BotEquityCurve, 'sc130BotEquityCurve'),
    n(AppRouteNames.sc131BotGuide, 'sc131BotGuide'),
    n(AppRouteNames.sc132BotFaq, 'sc132BotFaq'),
    n(AppRouteNames.sc133BotTaxReporting, 'sc133BotTaxReporting'),
    n(AppRouteNames.sc134BotApiDocumentation, 'sc134BotApiDocumentation'),
    n(AppRouteNames.sc411ClientOptUpRequest, 'sc411ClientOptUpRequest'),
    n(
      AppRouteNames.sc412TradeCopyRegulatoryDisclosuresAlias,
      'sc412TradeCopyRegulatoryDisclosuresAlias',
    ),
    n(
      AppRouteNames.sc415TargetMarketDefinitionDetail,
      'sc415TargetMarketDefinitionDetail',
    ),
    n(
      AppRouteNames.sc416ComplaintTrackingDetail,
      'sc416ComplaintTrackingDetail',
    ),
  ]);
}
