import 'package:vit_trade_flutter/app/router/app_router.dart';

import 'app_route_paths_contract_test_utils.dart';

void main() {
  routePathContractTest(
    'defines stable wallet profile DCA and admin route paths',
    [
      c(AppRoutePaths.settingsSecurity, '/settings/security'),
      c(AppRoutePaths.wallet, '/wallet'),
      c(AppRoutePaths.walletHistory, '/wallet/history'),
      c(AppRoutePaths.walletDeposit, '/wallet/deposit'),
      c(AppRoutePaths.walletDepositAsset('USDT'), '/wallet/deposit/USDT'),
      c(AppRoutePaths.walletWithdraw, '/wallet/withdraw'),
      c(AppRoutePaths.walletWithdrawAsset('USDT'), '/wallet/withdraw/USDT'),
      c(AppRoutePaths.walletTransaction('tx001'), '/wallet/transaction/tx001'),
      c(AppRoutePaths.walletPortfolioAnalytics, '/wallet/portfolio-analytics'),
      c(AppRoutePaths.walletAddressBook, '/wallet/address-book'),
      c(AppRoutePaths.walletAddressBookAdd, '/wallet/address-book/add'),
      c(AppRoutePaths.walletBuyCrypto, '/wallet/buy-crypto'),
      c(AppRoutePaths.walletTransfer, '/wallet/transfer'),
      c(AppRoutePaths.walletAsset('btc'), '/wallet/asset/btc'),
      c(AppRoutePaths.walletMultiManager, '/wallet/multi-manager'),
      c(AppRoutePaths.walletGasOptimizer, '/wallet/gas-optimizer'),
      c(AppRoutePaths.walletTokenApproval, '/wallet/token-approval'),
      c(AppRoutePaths.walletHealthScore, '/wallet/health-score'),
      c(AppRoutePaths.walletPendingDeposits, '/wallet/pending-deposits'),
      c(AppRoutePaths.walletLimits, '/wallet/limits'),
      c(AppRoutePaths.walletDustConverter, '/wallet/dust-converter'),
      c(AppRoutePaths.walletNetworkStatus, '/wallet/network-status'),
      c(AppRoutePaths.profile, '/profile'),
      c(AppRoutePaths.profileEdit, '/profile/edit'),
      c(AppRoutePaths.profileKyc, '/profile/kyc'),
      c(AppRoutePaths.profileSecurity, '/profile/security'),
      c(AppRoutePaths.profileVip, '/profile/vip'),
      c(AppRoutePaths.profileApi, '/profile/api'),
      c(AppRoutePaths.profileApiCreate, '/profile/api/create'),
      c(AppRoutePaths.profileDevices, '/profile/devices'),
      c(AppRoutePaths.profileSubAccounts, '/profile/sub-accounts'),
      c(AppRoutePaths.profileSettings, '/profile/settings'),
      c(AppRoutePaths.profileActivity, '/profile/activity'),
      c(AppRoutePaths.profileArena, '/profile/arena'),
      c(AppRoutePaths.onboarding, '/onboarding'),
      c(AppRoutePaths.dca, '/dca'),
      c(AppRoutePaths.dcaPortfolioOptimizer, '/dca/portfolio-optimizer'),
      c(AppRoutePaths.dcaDynamicAmount, '/dca/dynamic-amount'),
      c(AppRoutePaths.dcaRebalanceConfig, '/dca/rebalance/config'),
      c(AppRoutePaths.dcaRebalanceDashboard, '/dca/rebalance/config001'),
      c(
        AppRoutePaths.dcaRebalanceEdit('config001'),
        '/dca/rebalance/config001/edit',
      ),
      c(
        AppRoutePaths.dcaRebalanceHistory('config001'),
        '/dca/rebalance/config001/history',
      ),
      c(AppRoutePaths.dcaScheduleConfig, '/dca/schedule/config'),
      c(AppRoutePaths.dcaScheduleAnalytics, '/dca/schedule/config001'),
      c(AppRoutePaths.dcaBacktester, '/dca/backtester'),
      c(AppRoutePaths.dcaMultiAsset, '/dca/multi-asset'),
      c(AppRoutePaths.dcaPerformanceCompare, '/dca/performance-compare'),
      c(AppRoutePaths.dcaSmartRules, '/dca/smart-rules'),
      c(AppRoutePaths.admin, '/admin'),
      c(AppRoutePaths.adminAnalytics, '/admin/analytics'),
      c(AppRoutePaths.adminAbtests, '/admin/abtests'),
      c(AppRoutePaths.adminFunnels, '/admin/funnels'),
      c(AppRoutePaths.adminSettings, '/admin/settings'),
      c(
        AppRoutePaths.settingsSecurityBiometric,
        '/settings/security/biometric',
      ),
      c(
        AppRoutePaths.settingsSecurityChangePassword,
        '/settings/security/change-password',
      ),
    ],
  );
}
