import 'package:vit_trade_flutter/app/router/app_router.dart';

import 'app_route_paths_contract_test_utils.dart';

void main() {
  routePathContractTest('defines stable P2P route paths', [
    c(AppRoutePaths.p2p, '/p2p'),
    c(AppRoutePaths.p2pExpress, '/p2p/express'),
    c(AppRoutePaths.p2pExpressConfirm, '/p2p/express/confirm'),
    c(AppRoutePaths.p2pOrder('p2p001'), '/p2p/order/p2p001'),
    c(AppRoutePaths.p2pOrderTimeline('p2p001'), '/p2p/order/timeline/p2p001'),
    c(AppRoutePaths.p2pOrderRate('p2p001'), '/p2p/order/rate/p2p001'),
    c(AppRoutePaths.p2pOrderCancel('p2p001'), '/p2p/order/cancel/p2p001'),
    c(AppRoutePaths.p2pOrderProof('p2p001'), '/p2p/order/proof/p2p001'),
    c(AppRoutePaths.p2pChat('p2p001'), '/p2p/chat/p2p001'),
    c(AppRoutePaths.p2pDispute('p2p001'), '/p2p/dispute/p2p001'),
    c(AppRoutePaths.p2pDisputeDetail('sample'), '/p2p/dispute/detail/sample'),
    c(
      AppRoutePaths.p2pDisputeEvidence('disp001'),
      '/p2p/dispute/evidence/disp001',
    ),
    c(
      AppRoutePaths.p2pDisputeResolution('disp001'),
      '/p2p/dispute/resolution/disp001',
    ),
    c(AppRoutePaths.p2pDisputes, '/p2p/disputes'),
    c(AppRoutePaths.p2pAdAnalytics('sample'), '/p2p/ad-analytics/sample'),
    c(AppRoutePaths.p2pAd('sample'), '/p2p/ad/sample'),
    c(AppRoutePaths.p2pMyAds, '/p2p/my-ads'),
    c(AppRoutePaths.p2pCreate, '/p2p/create'),
    c(AppRoutePaths.p2pMerchantApply, '/p2p/merchant-apply'),
    c(AppRoutePaths.p2pEscrow('p2p001'), '/p2p/escrow/p2p001'),
    c(AppRoutePaths.p2pKycRequirements, '/p2p/kyc/requirements'),
    c(AppRoutePaths.p2pKycVerify, '/p2p/kyc/verify'),
    c(AppRoutePaths.p2pKycStatus, '/p2p/kyc/status'),
    c(AppRoutePaths.p2pKycIdentity, '/p2p/kyc/identity'),
    c(AppRoutePaths.p2pKycAddress, '/p2p/kyc/address'),
    c(AppRoutePaths.p2pKycSelfie, '/p2p/kyc/selfie'),
    c(AppRoutePaths.p2pKycVideo, '/p2p/kyc/video'),
    c(AppRoutePaths.p2pKycFaceMatch, '/p2p/kyc/face-match'),
    c(AppRoutePaths.p2pSecurityCenter, '/p2p/security/center'),
    c(AppRoutePaths.p2pSecurity2fa, '/p2p/security/2fa'),
    c(AppRoutePaths.p2pSecurityDevices, '/p2p/security/devices'),
    c(AppRoutePaths.p2pSecurityAntiPhishing, '/p2p/security/anti-phishing'),
    c(AppRoutePaths.p2pSecurityLoginHistory, '/p2p/security/login-history'),
    c(
      AppRoutePaths.p2pSecuritySuspiciousActivity,
      '/p2p/security/suspicious-activity',
    ),
    c(AppRoutePaths.p2pSecurityWhitelist, '/p2p/security/whitelist'),
    c(AppRoutePaths.p2pMerchant('mc001'), '/p2p/merchant/mc001'),
    c(AppRoutePaths.p2pReport('mc001'), '/p2p/report/mc001'),
    c(AppRoutePaths.p2pTradingLevel, '/p2p/trading-level'),
    c(AppRoutePaths.p2pBlacklist, '/p2p/blacklist'),
    c(AppRoutePaths.p2pBlacklistAdd, '/p2p/blacklist/add'),
    c(AppRoutePaths.p2pGuide, '/p2p/guide'),
    c(AppRoutePaths.p2pSettings, '/p2p/settings'),
    c(AppRoutePaths.p2pE2EInfo, '/p2p/e2e-info'),
    c(AppRoutePaths.p2pFraudPrevention, '/p2p/fraud-prevention'),
    c(AppRoutePaths.p2pWallet, '/p2p/wallet'),
    c(AppRoutePaths.p2pWalletTransfer, '/p2p/wallet/transfer'),
    c(AppRoutePaths.p2pWalletFundLockHistory, '/p2p/wallet/fund-lock-history'),
    c(AppRoutePaths.p2pWalletHistory, '/p2p/wallet/history'),
    c(AppRoutePaths.p2pLimits, '/p2p/limits'),
    c(AppRoutePaths.p2pLimitsTracker, '/p2p/limits/tracker'),
  ]);
}
